initScope: "monorepo-template"
nodeLinker: pnp
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
packageExtensions:
  "@nrwl/nx-cloud@*":
    dependencies:
      dotenv: "^16.0.1"
